const nombreEmpresa="RestrenaCar";
const users=[
            {
                id:"1",
                name:"Jimmy Ramos",
                sex:"man",
                password:"12345",
                email:"jimmyramos@gmail.com"
            },
            {
                id:"2",
                name:"Usuario prueba",
                sex:"man",
                password:"12345",
                email:"usertest@gmail.com"
            },
];

const coches=[
            {
                id: "1",
                marca: "BMW",
                modelo: "220i",
                year : "2014",
                kilometraje: "90.0000",
                potencia: "184cv",
                cambio: "automatic",
                precio: "23.790",
                combustible:"petrol",
                pegatina: "c",
                tipo: "coupe",
                vistas:"65"
                
            },
            {
                id: "2",
                marca: "BMW",
                modelo: "420d",
                year : "2015",
                kilometraje: "85.095",
                potencia: "190cv",
                cambio: "manual",
                precio: "22.390",
                combustible:"petrol",
                pegatina: "c",
                tipo: "coupe",
                vistas:"65"

            },
            {
                id: "3",
                marca: "BMW",
                modelo: "218d",
                year : "2014",
                kilometraje: "88.000",
                potencia: "143cv",
                cambio: "manual",
                precio: "16.790",
                combustible:"diesel",
                pegatina: "c",
                tipo: "coupe",
                vistas:"65"
            },
            {
                id: "4",
                marca: "Volkswagen",
                modelo: "CC BMT Advance",
                year : "2015",
                kilometraje: "85.050",
                potencia: "184cv",
                cambio: "automatic",
                precio: "18.990",
                combustible:"diesel",
                pegatina: "c",
                tipo: "coupe",
                vistas:"38"
            },
            {
                id: "5",
                marca: "Mercedes Benz",
                modelo: "E220 CDI",
                year : "2016",
                kilometraje: "85.050",
                potencia: "150cv",
                cambio: "manual",
                precio: "22.390",
                combustible:"diesel",
                pegatina: "b",
                tipo: "coupe",
                vistas:"40"
            },
            {
                id: "6",
                marca: "BMW",
                modelo: "430d",
                year : "2015",
                kilometraje: "204.809",
                potencia: "258cv",
                cambio: "automatic",
                precio: "19.190",
                combustible:"diesel",
                pegatina: "c",
                tipo: "coupe",
                vistas:"30"
            },{
                id: "7",
                marca: "Renault",
                modelo: "Megane",
                year : "2018",
                kilometraje: "43.000",
                potencia: "130cv",
                cambio: "manual",
                precio: "13.000",
                combustible:"diesel",
                pegatina: "c",
                tipo: "compacto",
                vistas:"65"
            },
            {
                id: "8",
                marca: "Citroen",
                modelo: "c3",
                year : "2017",
                kilometraje: "78.000",
                potencia: "82cv",
                cambio: "manual",
                precio: "9.690",
                combustible:"petrol",
                pegatina: "c",
                tipo: "compacto",
                vistas:"115"
            },
            {
                id: "9",
                marca: "Volkswagen",
                modelo: "Polo",
                year : "2017",
                kilometraje: "88.000",
                potencia: "143cv",
                cambio: "manual",
                precio: "8.000",
                combustible:"diesel",
                pegatina: "c",
                tipo: "compacto",
                vistas:"78"
            },
            {
                id: "10",
                marca: "Opel",
                modelo: "Astra",
                year : "2017",
                kilometraje: "75.000",
                potencia: "110cv",
                cambio: "automatic",
                precio: "9.790",
                combustible:"diesel",
                pegatina: "c",
                tipo: "compacto",
                vistas:"64"
            },
            {
                id: "11",
                marca: "Renault",
                modelo: "Kangoo Van",
                year : "2019",
                kilometraje: "96.000",
                potencia: "75cv",
                cambio: "manual",
                precio: "10.690",
                combustible:"petrol",
                pegatina: "c",
                tipo: "furgoneta",
                vistas:"63"
            },
            {
                id: "12",
                marca: "Peugeot",
                modelo: "Partner",
                year : "2017",
                kilometraje: "88.000",
                potencia: "100cv",
                cambio: "manual",
                precio: "12.000",
                combustible:"petrol",
                pegatina: "c",
                tipo: "furgoneta",
                vistas:"47"
            },
            {
                id: "13",
                marca: "Ford",
                modelo: "Transit",
                year : "2018",
                kilometraje: "117.000",
                potencia: "120cv",
                cambio: "manual",
                precio: "11.790",
                combustible:"diesel",
                pegatina: "c",
                tipo: "furgoneta",
                vistas:"36"
            },
            {
                id: "14",
                marca: "Peugeot 308",
                modelo: "SW Business Line",
                year : "2018",
                kilometraje: "75.000",
                potencia: "130cv",
                cambio: "automatic",
                precio: "9.790",
                combustible:"diesel",
                pegatina: "c",
                tipo: "familiar",
                vistas:"65"
            },
            {
                id: "15",
                marca: "Volkswagen Golf",
                modelo: "Advance 1.0 TSI",
                year : "2019",
                kilometraje: "60.000",
                potencia: "110cv",
                cambio: "automatic",
                precio: "17.690",
                combustible:"petrol",
                pegatina: "c",
                tipo: "familiar",
                vistas:"68"
            },
            {
                id: "16",
                marca: "Skoda Superb",
                modelo: "Van 1.6 TDI",
                year : "2017",
                kilometraje: "88.000",
                potencia: "120cv",
                cambio: "automatic",
                precio: "19.000",
                combustible:"diesel",
                pegatina: "c",
                tipo: "familiar",
                vistas:"144"

            },
            {
                id: "17",
                marca: "Mercedes clase C",
                modelo: "C 220 d Estate",
                year : "2019",
                kilometraje: "200.000",
                potencia: "194cv",
                cambio: "automatic",
                precio: "32.790",
                combustible:"petrol",
                pegatina: "c",
                tipo: "familiar",
                vistas:"118"
            },
            {
                id: "18",
                marca: "Peugeot 3008",
                modelo: "1.6 BlueHDI",
                year : "2019",
                kilometraje: "60.000",
                potencia: "120cv",
                cambio: "automatic",
                precio: "15.690",
                combustible:"petrol",
                pegatina: "c",
                tipo: "4x4suv",
                vistas:"68"
            },
            {
                id: "19",
                marca: "Fiat Freemont",
                modelo: "Lounge 2.0",
                year : "2013",
                kilometraje: "170.000",
                potencia: "140cv",
                cambio: "manual",
                precio: "11.690",
                combustible:"petrol",
                pegatina: "b",
                tipo: "4x4suv",
                vistas:"78"
            },
            {
                id: "20",
                marca: "Renault Captur",
                modelo: "Zen TCe 90",
                year : "2019",
                kilometraje: "80.000",
                potencia: "90cv",
                cambio: "automatic",
                precio: "10.690",
                combustible:"diesel",
                pegatina: "c",
                tipo: "4x4suv",
                vistas:"69"
            },
            {
                id: "21",
                marca: "Opel Zafira Tourer",
                modelo: "1.6 CDTi S/S",
                year : "2017",
                kilometraje: "94.000",
                potencia: "136cv",
                cambio: "manual",
                precio: "12.690",
                combustible:"petrol",
                pegatina: "c",
                tipo: "monovolumen",
                vistas:"45"
            },
            {
                id: "22",
                marca: "Renault Espace",
                modelo: "Initiale Paris Energy",
                year : "2016",
                kilometraje: "80.000",
                potencia: "160cv",
                cambio: "automatic",
                precio: "10.690",
                combustible:"diesel",
                pegatina: "c",
                tipo: "monovolumen",
                vistas:"80"
            },
            {
                id: "23",
                marca: "Citroen C4 Spacetourer",
                modelo: "BlueHDI 88KW",
                year : "2019",
                kilometraje: "115.000",
                potencia: "120cv",
                cambio: "manual",
                precio: "13.690",
                combustible:"petrol",
                pegatina: "c",
                tipo: "monovolumen",
                vistas:"79"
            },
            {
                id: "24",
                marca: "MINI MINI",
                modelo: "Cooper D Cabrio",
                year : "2017",
                kilometraje: "94.000",
                potencia: "116cv",
                cambio: "automatic",
                precio: "12.690",
                combustible:"petrol",
                pegatina: "c",
                tipo: "cabrio",
                vistas:"245"
            },
            {
                id: "25",
                marca: "Mazda MX-5",
                modelo: "2.0 135KW Zenith ST",
                year : "2021",
                kilometraje: "11.000",
                potencia: "160cv",
                cambio: "automatic",
                precio: "24.690",
                combustible:"petrol",
                pegatina: "c",
                tipo: "cabrio",
                vistas:"285"
            },
            {
                id: "26",
                marca: "Mercedes Clase C",
                modelo: "C Cabrio 200",
                year : "2018",
                kilometraje: "115.000",
                potencia: "120cv",
                cambio: "automatic",
                precio: "40.690",
                combustible:"petrol",
                pegatina: "c",
                tipo: "cabrio",
                vistas:"145"
            },
            {
                id: "27",
                marca: "BMW Serie 3",
                modelo: "320i Auto",
                year : "2020",
                kilometraje: "138.000",
                potencia: "184cv",
                cambio: "automatic",
                precio: "31.690",
                combustible:"petrol",
                pegatina: "c",
                tipo: "berlina",
                vistas:"147"
            },
            {
                id: "28",
                marca: "Audi A5",
                modelo: "S Line 40 TFSI",
                year : "2021",
                kilometraje: "15.000",
                potencia: "204cv",
                cambio: "automatic",
                precio: "37.690",
                combustible:"petrol",
                pegatina: "c",
                tipo: "berlina",
                vistas:"117"
            },
            {
                id: "29",
                marca: "Mercedes Clase E",
                modelo: "E 350 d",
                year : "2017",
                kilometraje: "55.000",
                potencia: "258cv",
                cambio: "automatic",
                precio: "33.690",
                combustible:"petrol",
                pegatina: "c",
                tipo: "berlina",
                vistas:"205"
            }

];

